name: Snake
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-snake
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#FF1A1A&color_dots=#16161e,#440000,#990000,#FF1A1A,#FF6666

      - name: Commit & Push snake
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/github-snake.svg dist/github-snake-dark.svg
          git commit -m "generated snake" || exit 0
          git push
